import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Every docs instance reads this file and builds its `docs` sidebar from its
// own folder: `_category_.json` files group pages, `sidebar_position` orders them.
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
